name: Go Tests

on:
  push:
    branches:
      - main # or the branch you want to run tests on
  pull_request:
    branches:
      - main # or the branch you want to run tests on

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.23.0"

      - name: Run tests
        run: |
          go test -v ./...
